### ISSUE TITLE
Parsing subcommand failiure: gitbr `git cbranch`.bak

### ISSUE THREAD

**Issue by zdennis** [zdennis/yap-shell-parser#1]
The following command fails:

```
gitbr `git cbranch`.bak
```

with this error:

```
/Users/zdennis/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error':  (Racc::ParseError)
parse error on value :BeginSubcommand '`' {} (error)
    from grammar.y:89:in `_racc_do_parse_c'
    from grammar.y:89:in `parse'
    from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/evaluation.rb:14:in `evaluate'
    from /Users/zdennis/source/playground/yap-shell/lib/yap/shell.rb:46:in `block in repl'
    from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/repl.rb:24:in `block in loop_on_input'
    from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/repl.rb:12:in `loop'
    from /Users/zdennis/source/playground/yap-shell/lib/yap/shell/repl.rb:12:in `loop_on_input'
    from /Users/zdennis/source/playground/yap-shell/lib/yap/shell.rb:44:in `repl'
    from /Users/zdennis/source/playground/yap-shell/lib/yap.rb:61:in `run_shell'
    from /Users/zdennis/bin/yap:20:in `<main>'
```

**Comment by zdennis** [comment]
This has been resolved in the 0.1.0 release of the yap-shell-parser gem.  See https://github.com/zdennis/yap-shell-parser/compare/32e242d...ac3f3a4 specifically.
